config-version: 1
properties:
  # Show debug messages.
  debug-messages: false

  # Check a chunk upon load (ChunkLoadEvent).
  check-chunk-load: false

  # Check a chunk upon unload (ChunkUnloadEvent).
  check-chunk-unload: false

  # Check a chunk when a mob spawns (CreatureSpawnEvent).
  watch-creature-spawns: true

  # Prevent new spawns rather than cull older entities until cap is hit.
  prevent-creature-spawns: false

  # Radius of surrounding chunks to check.
  check-surrounding-chunks: 1

  # When a chunk is loaded, recheck it periodically.
  active-inspections: true

  # How often, in seconds, to check the chunk.
  inspection-frequency: 300

  # Notify players in that chunk if stuff has been culled.
  notify-players: false

  # Prioritize entities without names over older entities.
  preserve-named-entities: true

  # Ignore entities with any of the following metadata.
  ignore-metadata:
  - shopkeeper

# Spawn reasons to cull on.
spawn-reasons:
  BREEDING: true
  BUILD_IRONGOLEM: true
  BUILD_SNOWMAN: true
  BUILD_WITHER: true
  CURED: false
  CUSTOM: true
  DEFAULT: true
  DISPENSE_EGG: true
  DROWNED: false
  EGG: true
  ENDER_PEARL: true
  EXPLOSION: false
  INFECTION: false
  JOCKEY: true
  LIGHTNING: true
  MOUNT: true
  NATURAL: true
  NETHER_PORTAL: true
  OCELOT_BABY: true
  REINFORCEMENTS: true
  SHEARED: false
  SHOULDER_ENTITY: false
  SILVERFISH_BLOCK: true
  SLIME_SPLIT: true
  SPAWNER: true
  SPAWNER_EGG: true
  TRAP: true
  VILLAGE_DEFENSE: true
  VILLAGE_INVASION: true

entities:
  ANIMAL: 50
  MONSTER: 50
  NPC: 50
  OTHER: 500
#  GOLEM: 5
#  WATER_MOB: 5
#  AMBIENT: 5

#  CREEPER: 10
#  SHEEP: 10
#  OCELOT: 10
#  GIANT: 10
#  SLIME: 10
#  GHAST: 10
#  PIG_ZOMBIE: 10
#  ENDERMAN: 10
#  SILVERFISH: 10
#  MAGMA_CUBE: 10
#  CHICKEN: 10
#  SQUID: 10
#  WOLF: 10
#  MUSHROOM_COW: 10
#  SNOWMAN: 10
#  VILLAGER: 10
#  SPIDER: 10
#  SKELETON: 10
#  ZOMBIE: 10
#  BLAZE: 10
#  CAVE_SPIDER: 10
#  IRON_GOLEM: 10
#  WITHER: 10
#  PIG: 10
#  HORSE: 10
#  WITCH: 10
#  MINECART_HOPPER: 16
#  MINECART_CHEST: 16
#  MINECART: 30

# Exclude these worlds from limits.
excluded-worlds: []

messages:
  removedEntites: "&4[&bCSL&4] &7Removed %s %s in your chunk."
