name: ChunkSpawnerLimiter
main: com.cyprias.chunkspawnerlimiter.ChunkSpawnerLimiterPlugin
authors: [Cyprias, Jikoo, selfslaughter]
description: ${project.description}
version: ${project.version}
api-version: "1.14"

permissions:
 chunkspawnerlimiter.admin:
  default: op
  description: Permission to use administrative commands for CSL.

commands:
 chunkspawnerlimiter:
   aliases: [csl]
   description: Command for controlling ChunkSpawnerLimiter.
   permission: chunkspawnerlimiter.admin
   usage: /<command> reload
