name: ChunkSpawnerLimiter
main: com.cyprias.chunkspawnerlimiter.ChunkSpawnerLimiterPlugin
author: Cyprias
authors: [Jikoo]
description: Limit entities in a chunk.
version: ${project.version}

permissions:
 chunkspawnerlimiter.admin:
  default: op
  description: Permission to use administrative commands for CSL.

commands:
 chunkspawnerlimiter:
   aliases: [csl]
   description: Command for controlling ChunkSpawnerLimiter.
   permission: chunkspawnerlimiter.admin
   usage: /<command> reload
